from enum import Enum


class HttpCodes(Enum):

    OK = (200, 'OK')
    CREATED = (201, 'CREATED')
    ACCEPTED = (202, 'ACCEPTED')
    NON_AUTHORITATIVE_INFORMATION = (203, 'NON_AUTHORITATIVE_INFORMATION')
    NO_CONTENT = (204, 'NO_CONTENT')
    RESET_CONTENT = (205, 'RESET_CONTENT')
    PARTIAL_CONTENT = (206, 'PARTIAL_CONTENT')

    MULTIPLE_CHOICES = (300, 'MULTIPLE_CHOICES')
    MOVED_PERMANENTLY = (301, 'MOVED_PERMANENTLY')
    FOUND = (302, 'FOUND')
    SEE_OTHER = (303, 'SEE_OTHER')
    NOT_MODIFIED = (304, 'NOT_MODIFIED')
    TEMPORARY_REDIRECT = (307, 'TEMPORARY_REDIRECT')
    PERMANENT_REDIRECT = (308, 'PERMANENT_REDIRECT')

    BAD_REQUEST = (400, 'BAD_REQUEST')
    UNAUTHORIZED = (401, 'UNAUTHORIZED')
    FORBIDDEN = (403, 'FORBIDDEN')
    NOT_FOUND = (404, 'NOT_FOUND')
    METHOD_NOT_ALLOWED = (405, 'METHOD_NOT_ALLOWED')
    CONFLICT = (409, 'CONFLICT')
    GONE = (410, 'GONE')
    PRECONDITION_FAILED = (412, 'PRECONDITION_FAILED')
    PAYLOAD_TOO_LARGE = (413, 'PAYLOAD_TOO_LARGE')
    UNSUPPORTED_MEDIA_TYPE = (415, 'UNSUPPORTED_MEDIA_TYPE')
    RANGE_NOT_SATISFIABLE = (416, 'RANGE_NOT_SATISFIABLE')
    EXPECTATION_FAILED = (417, 'EXPECTATION_FAILED')
    UNPROCESSABLE_ENTITY = (422, 'UNPROCESSABLE_ENTITY')
    UPGRADE_REQUIRED = (426, 'UPGRADE_REQUIRED')
    TOO_MANY_REQUESTS = (429, 'TOO_MANY_REQUESTS')

    INTERNAL_SERVER_ERROR = (500, 'INTERNAL_SERVER_ERROR')
    NOT_IMPLEMENTED = (501, 'NOT_IMPLEMENTED')
    BAD_GATEWAY = (502, 'BAD_GATEWAY')
    SERVICE_UNAVAILABLE = (503, 'SERVICE_UNAVAILABLE')
    GATEWAY_TIMEOUT = (504, 'GATEWAY_TIMEOUT')
    HTTP_VERSION_NOT_SUPPORTED = (505, 'HTTP_VERSION_NOT_SUPPORTED')
    INSUFFICIENT_STORAGE = (507, 'INSUFFICIENT_STORAGE')