name: Pipeline CI/CD

on:
  push:
    branches:
      - feature/quotation

permissions:
  id-token: write
  contents: read

jobs:
    build:
      name: build_ecr
      runs-on: ubuntu-latest
#      environment: "prod"
      outputs:
        image-uri: ${{ steps.login-ecr.outputs.registry }}
      steps:
        - name: Checkout
          uses: actions/checkout@v6.0.1

        - name: Configure AWS Credentials Action for GitHub Actions
          uses: aws-actions/configure-aws-credentials@v5.1.1
          with:
            role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Amazon ECR "Login" Action for GitHub Actions
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2.0.1
          with:
            region: ${{ secrets.AWS_REGION }}

        - name: teste
          run: echo ${{ steps.build.outputs.image-uri }}

#        - name: Build, Tag, and Push
#          run: |
#            docker build -t b3-assets:v1.0 .
#            docker tag b3-assets:v1.0 ${{ AWS_ECR_REPO }}:v1.0
#            docker push ${{ AWS_ECR_REPO }}:v1.0
#
#
#    deploy:
#      needs: build
#      name: deploy_ec2
#      runs-on: ubuntu:latest
#      steps:
#        - name: Deploy EC2 SSH
#          run: |
#            echo ${{ secrets.INSTANCE_KEY }} > key.pem
#            chmod 400 key.pem
#            ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.PUBLIC_IP }} << EOF
#              aws ecr get-login-password --region ${secrets.AWS_REGION} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR}}
#              docker pull ${{ secrets.AWS_ECR_REPO }}:v1.0
#
#              docker stop b3-assets || true
#              docker rm b3-assets || true
#
#              docker run -d -p 5000:5000 --name b3-assets ${{ secrets.AWS_ECR_REPO }}:v1.0
#
#            EOF
#            rm key.pem
